-- ========================================
-- Database_library_manager
-- Author: Lukáš Dvoøák
-- Email: dvorak13@spsejecna.cz
-- ========================================

USE master;
GO

-- =====================
-- CREATE DATABASE
-- =====================
IF DB_ID('dvorak13') IS NULL
BEGIN
    CREATE DATABASE dvorak13;
END
GO

USE dvorak13;
GO

-- =====================
-- DATABASE SETTINGS
-- =====================
ALTER DATABASE dvorak13 SET COMPATIBILITY_LEVEL = 170;
ALTER DATABASE dvorak13 SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE dvorak13 SET ANSI_NULLS OFF;
ALTER DATABASE dvorak13 SET ANSI_PADDING OFF;
ALTER DATABASE dvorak13 SET ANSI_WARNINGS OFF;
ALTER DATABASE dvorak13 SET ARITHABORT OFF;
ALTER DATABASE dvorak13 SET AUTO_CLOSE OFF;
ALTER DATABASE dvorak13 SET AUTO_SHRINK OFF;
ALTER DATABASE dvorak13 SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE dvorak13 SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE dvorak13 SET CURSOR_DEFAULT GLOBAL;
ALTER DATABASE dvorak13 SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE dvorak13 SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE dvorak13 SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE dvorak13 SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE dvorak13 SET ENABLE_BROKER;
ALTER DATABASE dvorak13 SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE dvorak13 SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE dvorak13 SET TRUSTWORTHY OFF;
ALTER DATABASE dvorak13 SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE dvorak13 SET PARAMETERIZATION SIMPLE;
ALTER DATABASE dvorak13 SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE dvorak13 SET HONOR_BROKER_PRIORITY OFF;
ALTER DATABASE dvorak13 SET RECOVERY FULL;
ALTER DATABASE dvorak13 SET MULTI_USER;
ALTER DATABASE dvorak13 SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE dvorak13 SET DB_CHAINING OFF;
ALTER DATABASE dvorak13 SET TARGET_RECOVERY_TIME = 60 SECONDS;
ALTER DATABASE dvorak13 SET DELAYED_DURABILITY = DISABLED;
ALTER DATABASE dvorak13 SET ACCELERATED_DATABASE_RECOVERY = OFF;
ALTER DATABASE dvorak13 SET OPTIMIZED_LOCKING = OFF;
GO

-- =====================
-- TABLES
-- =====================

IF OBJECT_ID('BDBgenre','U') IS NULL
CREATE TABLE BDBgenre (
    id INT IDENTITY(1,1) PRIMARY KEY,
    genre VARCHAR(50)
);
GO

IF OBJECT_ID('BDBauthor','U') IS NULL
CREATE TABLE BDBauthor (
    id INT IDENTITY(1,1) PRIMARY KEY,
    firstName VARCHAR(50),
    lastName VARCHAR(50)
);
GO

IF OBJECT_ID('BDBuser','U') IS NULL
CREATE TABLE BDBuser (
    id INT IDENTITY(1,1) PRIMARY KEY,
    username VARCHAR(50),
    email VARCHAR(50)
);
GO

IF OBJECT_ID('BDBbooks','U') IS NULL
CREATE TABLE BDBbooks (
    id INT IDENTITY(1,1) PRIMARY KEY,
    title VARCHAR(50),
    price DECIMAL(10,2),
    available BIT,
    state VARCHAR(50) NOT NULL,
    genre_id INT,
    author_id INT,
    CONSTRAINT CK_BDBbooks_state CHECK (state IN ('Used','Torn','Damaged','New'))
);
GO

IF OBJECT_ID('BDBloan','U') IS NULL
CREATE TABLE BDBloan (
    id INT IDENTITY(1,1) PRIMARY KEY,
    pickUpDate DATE,
    returnDate DATE,
    us_id INT,
    book_id INT
);
GO

-- =====================
-- FOREIGN KEYS
-- =====================

ALTER TABLE BDBbooks
ADD CONSTRAINT FK_BDBbooks_author
FOREIGN KEY (author_id) REFERENCES BDBauthor(id);
GO

ALTER TABLE BDBbooks
ADD CONSTRAINT FK_BDBbooks_genre
FOREIGN KEY (genre_id) REFERENCES BDBgenre(id);
GO

ALTER TABLE BDBloan
ADD CONSTRAINT FK_BDBloan_book
FOREIGN KEY (book_id) REFERENCES BDBbooks(id);
GO

ALTER TABLE BDBloan
ADD CONSTRAINT FK_BDBloan_user
FOREIGN KEY (us_id) REFERENCES BDBuser(id);
GO

-- =====================
-- VIEWS
-- =====================

CREATE OR ALTER VIEW bookLoanView AS
SELECT
    b.title AS BookTitle,
    g.genre AS Genre,
    COUNT(l.id) AS LoanCount,
    MIN(l.pickUpDate) AS FirstLoan,
    MAX(l.returnDate) AS LastReturn
FROM BDBbooks b
JOIN BDBgenre g ON b.genre_id = g.id
LEFT JOIN BDBloan l ON l.book_id = b.id
GROUP BY b.title, g.genre;
GO

CREATE OR ALTER VIEW authorLoanView AS
SELECT
    a.firstName + ' ' + a.lastName AS AuthorName,
    COUNT(l.id) AS LoanCount,
    MIN(l.pickUpDate) AS FirstLoan,
    MAX(l.pickUpDate) AS LastLoan
FROM BDBauthor a
JOIN BDBbooks b ON b.author_id = a.id
JOIN BDBloan l ON l.book_id = b.id
GROUP BY a.firstName, a.lastName;
GO
-- ========================================
-- Database_library_manager
-- Author: Lukáš Dvoøák
-- Email: dvorak13@spsejecna.cz
-- ========================================

USE master;
GO

-- =====================
-- CREATE DATABASE
-- =====================
IF DB_ID('dvorak13') IS NULL
BEGIN
    CREATE DATABASE dvorak13;
END
GO

USE dvorak13;
GO

-- =====================
-- DATABASE SETTINGS
-- =====================
ALTER DATABASE dvorak13 SET COMPATIBILITY_LEVEL = 170;
ALTER DATABASE dvorak13 SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE dvorak13 SET ANSI_NULLS OFF;
ALTER DATABASE dvorak13 SET ANSI_PADDING OFF;
ALTER DATABASE dvorak13 SET ANSI_WARNINGS OFF;
ALTER DATABASE dvorak13 SET ARITHABORT OFF;
ALTER DATABASE dvorak13 SET AUTO_CLOSE OFF;
ALTER DATABASE dvorak13 SET AUTO_SHRINK OFF;
ALTER DATABASE dvorak13 SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE dvorak13 SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE dvorak13 SET CURSOR_DEFAULT GLOBAL;
ALTER DATABASE dvorak13 SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE dvorak13 SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE dvorak13 SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE dvorak13 SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE dvorak13 SET ENABLE_BROKER;
ALTER DATABASE dvorak13 SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE dvorak13 SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE dvorak13 SET TRUSTWORTHY OFF;
ALTER DATABASE dvorak13 SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE dvorak13 SET PARAMETERIZATION SIMPLE;
ALTER DATABASE dvorak13 SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE dvorak13 SET HONOR_BROKER_PRIORITY OFF;
ALTER DATABASE dvorak13 SET RECOVERY FULL;
ALTER DATABASE dvorak13 SET MULTI_USER;
ALTER DATABASE dvorak13 SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE dvorak13 SET DB_CHAINING OFF;
ALTER DATABASE dvorak13 SET TARGET_RECOVERY_TIME = 60 SECONDS;
ALTER DATABASE dvorak13 SET DELAYED_DURABILITY = DISABLED;
ALTER DATABASE dvorak13 SET ACCELERATED_DATABASE_RECOVERY = OFF;
ALTER DATABASE dvorak13 SET OPTIMIZED_LOCKING = OFF;
GO

-- =====================
-- TABLES
-- =====================

IF OBJECT_ID('BDBgenre','U') IS NULL
CREATE TABLE BDBgenre (
    id INT IDENTITY(1,1) PRIMARY KEY,
    genre VARCHAR(50)
);
GO

IF OBJECT_ID('BDBauthor','U') IS NULL
CREATE TABLE BDBauthor (
    id INT IDENTITY(1,1) PRIMARY KEY,
    firstName VARCHAR(50),
    lastName VARCHAR(50)
);
GO

IF OBJECT_ID('BDBuser','U') IS NULL
CREATE TABLE BDBuser (
    id INT IDENTITY(1,1) PRIMARY KEY,
    username VARCHAR(50),
    email VARCHAR(50)
);
GO

IF OBJECT_ID('BDBbooks','U') IS NULL
CREATE TABLE BDBbooks (
    id INT IDENTITY(1,1) PRIMARY KEY,
    title VARCHAR(50),
    price DECIMAL(10,2),
    available BIT,
    state VARCHAR(50) NOT NULL,
    genre_id INT,
    author_id INT,
    CONSTRAINT CK_BDBbooks_state CHECK (state IN ('Used','Torn','Damaged','New'))
);
GO

IF OBJECT_ID('BDBloan','U') IS NULL
CREATE TABLE BDBloan (
    id INT IDENTITY(1,1) PRIMARY KEY,
    pickUpDate DATE,
    returnDate DATE,
    us_id INT,
    book_id INT
);
GO

-- =====================
-- FOREIGN KEYS
-- =====================

ALTER TABLE BDBbooks
ADD CONSTRAINT FK_BDBbooks_author
FOREIGN KEY (author_id) REFERENCES BDBauthor(id);
GO

ALTER TABLE BDBbooks
ADD CONSTRAINT FK_BDBbooks_genre
FOREIGN KEY (genre_id) REFERENCES BDBgenre(id);
GO

ALTER TABLE BDBloan
ADD CONSTRAINT FK_BDBloan_book
FOREIGN KEY (book_id) REFERENCES BDBbooks(id);
GO

ALTER TABLE BDBloan
ADD CONSTRAINT FK_BDBloan_user
FOREIGN KEY (us_id) REFERENCES BDBuser(id);
GO

-- =====================
-- VIEWS
-- =====================

CREATE OR ALTER VIEW bookLoanView AS
SELECT
    b.title AS BookTitle,
    g.genre AS Genre,
    COUNT(l.id) AS LoanCount,
    MIN(l.pickUpDate) AS FirstLoan,
    MAX(l.returnDate) AS LastReturn
FROM BDBbooks b
JOIN BDBgenre g ON b.genre_id = g.id
LEFT JOIN BDBloan l ON l.book_id = b.id
GROUP BY b.title, g.genre;
GO

CREATE OR ALTER VIEW authorLoanView AS
SELECT
    a.firstName + ' ' + a.lastName AS AuthorName,
    COUNT(l.id) AS LoanCount,
    MIN(l.pickUpDate) AS FirstLoan,
    MAX(l.pickUpDate) AS LastLoan
FROM BDBauthor a
JOIN BDBbooks b ON b.author_id = a.id
JOIN BDBloan l ON l.book_id = b.id
GROUP BY a.firstName, a.lastName;
GO
