/* Database_library_manager, Lukáš Dvoøák, dvorak13@spsejecna.cz */
USE [master]
GO
/****** Object:  Database [dvorak13]    Script Date: 10.01.2026 22:15:36 ******/
CREATE DATABASE [dvorak13]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dvorak13', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\dvorak13.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dvorak13_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\dvorak13_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [dvorak13] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dvorak13].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dvorak13] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dvorak13] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dvorak13] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dvorak13] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dvorak13] SET ARITHABORT OFF 
GO
ALTER DATABASE [dvorak13] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dvorak13] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dvorak13] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dvorak13] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dvorak13] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dvorak13] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dvorak13] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dvorak13] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dvorak13] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dvorak13] SET  ENABLE_BROKER 
GO
ALTER DATABASE [dvorak13] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dvorak13] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dvorak13] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dvorak13] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dvorak13] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dvorak13] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dvorak13] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dvorak13] SET RECOVERY FULL 
GO
ALTER DATABASE [dvorak13] SET  MULTI_USER 
GO
ALTER DATABASE [dvorak13] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dvorak13] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dvorak13] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dvorak13] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [dvorak13] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [dvorak13] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [dvorak13] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [dvorak13] SET QUERY_STORE = ON
GO
ALTER DATABASE [dvorak13] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [dvorak13]
GO
/****** Object:  Table [dbo].[BDBgenre]    Script Date: 10.01.2026 22:15:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BDBgenre](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[genre] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BDBbooks]    Script Date: 10.01.2026 22:15:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BDBbooks](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[title] [varchar](50) NULL,
	[price] [decimal](10, 2) NULL,
	[available] [bit] NULL,
	[state] [varchar](50) NOT NULL,
	[genre_id] [int] NULL,
	[author_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BDBloan]    Script Date: 10.01.2026 22:15:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BDBloan](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[pickUpDate] [date] NULL,
	[returnDate] [date] NULL,
	[us_id] [int] NULL,
	[book_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[bookLoanView]    Script Date: 10.01.2026 22:15:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create view [dbo].[bookLoanView] as
select BDBbooks.title as BookTitle, BDBgenre.genre as Genre, count(BDBloan.id) as LoanCount, min(BDBloan.pickUpDate) as FirstLoan, max(BDBloan.returnDate) as LastReturn from BDBbooks
join BDBgenre on BDBbooks.genre_id = BDBgenre.id
left join BDBloan on BDBloan.book_id = BDBbooks.id
group by BDBbooks.title, BDBgenre.genre;

GO
/****** Object:  Table [dbo].[BDBauthor]    Script Date: 10.01.2026 22:15:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BDBauthor](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[firstName] [varchar](50) NULL,
	[lastName] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[authorLoanView]    Script Date: 10.01.2026 22:15:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create view [dbo].[authorLoanView] as
select BDBauthor.firstName + ' ' + BDBauthor.lastName as AuthorName, count(BDBloan.id) as LoanCount, min(BDBloan.PickUpDate) as FirstLoan, max(BDBloan.PickUpDate) as LastLoan from BDBauthor
join BDBbooks ON BDBbooks.author_id = BDBauthor.id
join BDBloan ON BDBloan.book_id = BDBbooks.id
group by BDBauthor.firstName, BDBauthor.lastName;

GO
/****** Object:  Table [dbo].[BDBuser]    Script Date: 10.01.2026 22:15:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BDBuser](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NULL,
	[email] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BDBbooks]  WITH CHECK ADD FOREIGN KEY([author_id])
REFERENCES [dbo].[BDBauthor] ([id])
GO
ALTER TABLE [dbo].[BDBbooks]  WITH CHECK ADD FOREIGN KEY([genre_id])
REFERENCES [dbo].[BDBgenre] ([id])
GO
ALTER TABLE [dbo].[BDBloan]  WITH CHECK ADD FOREIGN KEY([book_id])
REFERENCES [dbo].[BDBbooks] ([id])
GO
ALTER TABLE [dbo].[BDBloan]  WITH CHECK ADD FOREIGN KEY([us_id])
REFERENCES [dbo].[BDBuser] ([id])
GO
ALTER TABLE [dbo].[BDBbooks]  WITH CHECK ADD CHECK  (([state]='Used' OR [state]='Torn' OR [state]='Damaged' OR [state]='New'))
GO
USE [master]
GO
ALTER DATABASE [dvorak13] SET  READ_WRITE 
GO
